//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParcialCelesteCrud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Videojuegos
    {
        public int VideojuegoId { get; set; }
        public string nombre { get; set; }
        public decimal precio { get; set; }
        public int stock { get; set; }
        public Nullable<System.DateTime> fecha_lanzamiento { get; set; }
        public Nullable<int> CategoriaId { get; set; }
    }
}
